# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCashflow():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_approve(self):
    self.driver.get("https://exgnosis.org/cashflow/")
    self.driver.find_element(By.LINK_TEXT, "Line of Credit Calculator").click()
    self.driver.find_element(By.ID, "income").send_keys("50000")
    self.driver.find_element(By.ID, "credit").send_keys("750")
    self.driver.find_element(By.ID, "employment").send_keys("180")
    self.driver.find_element(By.NAME, "Calc").click()
    self.driver.find_element(By.CSS_SELECTOR, "h3:nth-child(2)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h3:nth-child(2)").text == "Please apply Today!!"
    self.driver.close()
  
  def test_lowIncome(self):
    self.driver.get("https://exgnosis.org/cashflow/")
    self.driver.find_element(By.LINK_TEXT, "Line of Credit Calculator").click()
    self.driver.find_element(By.ID, "income").send_keys("49999")
    self.driver.find_element(By.ID, "credit").send_keys("750")
    self.driver.find_element(By.ID, "employment").send_keys("180")
    self.driver.find_element(By.NAME, "Calc").click()
    self.driver.find_element(By.CSS_SELECTOR, "h3:nth-child(2)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h3:nth-child(2)").text == "Your Income is too low"
    self.driver.close()
  
